#!/usr/bin/env python3
"""Fetch official JGSA Block Tulna snapshot into official_block_scorecard.js.
This updates ONLY the Block Tulna source file. It does not touch data.js or main dashboard workflow.
"""
import json, os, re, urllib.request, html
from pathlib import Path

DISTRICT = os.environ.get('JGSA_BLOCK_DISTRICT','SATNA')
DATE = os.environ.get('JGSA_BLOCK_DATE','2026-06-03')
URL = f'https://jgsa.nregsmp.org/rankings.php?level=block&date={DATE}&district={DISTRICT}'
OUT = Path('official_block_scorecard.js')

CATEGORIES = ['Farm Pond','Amrit Sarowar','Dug Well Recharge','Irrigation infrastructure','Water conservation & recharge','Watershed Related Works','Repair & Maintenance (Water Structures)','Gap Filling in Plantation','Work Not Permissible in VB-GRAM-G']

def text_from_html(raw):
    raw = re.sub(r'<script[\s\S]*?</script>|<style[\s\S]*?</style>', ' ', raw, flags=re.I)
    raw = re.sub(r'<[^>]+>', '\n', raw)
    raw = html.unescape(raw)
    raw = re.sub(r'\n\s*\n+', '\n', raw)
    return raw

def load_existing():
    if not OUT.exists(): return None
    s = OUT.read_text(encoding='utf-8', errors='ignore')
    m = re.search(r'window\.OFFICIAL_JGSA_BLOCK_SCORECARD\s*=\s*(\{[\s\S]*?\});', s)
    if not m: return None
    try: return json.loads(m.group(1).replace("'", '"'))
    except Exception: return None

def write(data):
    OUT.write_text('// Auto-generated by scripts/fetch_official_block_scorecard.py\nwindow.OFFICIAL_JGSA_BLOCK_SCORECARD = '+json.dumps(data, ensure_ascii=False, indent=2)+';\n', encoding='utf-8')

try:
    with urllib.request.urlopen(URL, timeout=40) as r:
        raw = r.read().decode('utf-8', 'ignore')
    t = text_from_html(raw)
    # Parse block row headers like: "1 MAJHGAWAN ↗ 5.70 D"
    header_re = re.compile(r'(?m)^\s*(\d+)\s+([A-Z ]+?)\s*↗\s*([0-9]+\.[0-9]+)\s+([A-D])\s*$')
    headers = list(header_re.finditer(t))
    rows=[]
    for idx,h in enumerate(headers):
        rank=int(h.group(1)); block=h.group(2).strip(); score=float(h.group(3)); grade=h.group(4)
        seg=t[h.end(): headers[idx+1].start() if idx+1 < len(headers) else len(t)]
        cats={}
        for cidx,cat in enumerate(CATEGORIES):
            cstart=seg.find('Category '+cat)
            if cstart<0: continue
            cseg=seg[cstart:]
            next_positions=[cseg.find('Category '+x,1) for x in CATEGORIES if cseg.find('Category '+x,1)>0]
            if next_positions: cseg=cseg[:min(next_positions)]
            wt_match = re.search(r'([0-9]+\.[0-9]+)%\s+([0-9]+\.[0-9]+)\s+\n\s*Category\s+'+re.escape(cat), seg[:cstart+len('Category '+cat)+50], re.S)
            # fallback: score from Final score
            fs=re.search(r'Final score\s*([0-9]+\.[0-9]+)\s*/\s*10', cseg)
            cnt=re.search(r'Started\s*/\s*Completed\s*/\s*Phys\s*([0-9]+)\s*/\s*([0-9]+)\s*/\s*([0-9]+)', cseg)
            # weight is shown immediately before Category; search small window ending at category start
            before=seg[max(0,cstart-80):cstart]
            wm=re.findall(r'([0-9]+\.[0-9]+)%\s+([0-9]+\.[0-9]+)', before)
            weight=float(wm[-1][0]) if wm else 0.0
            sc=float(fs.group(1)) if fs else (float(wm[-1][1]) if wm else 0.0)
            cats[cat]={'weight':weight,'score':sc,'counts':'/'.join(cnt.groups()) if cnt else ''}
        rows.append({'rank':rank,'block':block,'score':score,'grade':grade,'completed':None,'started':None,'cats':cats})
    if len(rows) < 8:
        raise RuntimeError(f'Parsed only {len(rows)} rows')
    data={'source_url':URL,'snapshot':DATE,'district':DISTRICT,'scheme':'₹ Sanction Weighted','categories':CATEGORIES,'rows':rows[:8]}
    write(data)
    print(f'Wrote {OUT} with {len(data["rows"])} rows')
except Exception as e:
    print('Official block scorecard fetch failed:', e)
    print('Keeping existing official_block_scorecard.js unchanged')
